imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: demande
        connections:
            default:
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8
                mapping_types:
                    enum: string
            demande:
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: formdgseb
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8
                mapping_types:
                    enum: string

    orm:
        default_entity_manager: demande
        entity_managers:
            default:
                connection: default
                mappings:
                    GSEBMainBundle: ~   
                    GSEBDemandeBundle: ~
                    #GSEBUserBundle: ~
            demande:
                connection : demande
                mappings:
                    GSEBMainBundle: ~                   
                    GSEBDemandeBundle: ~
                    #GSEBUserBundle: ~
                   #FOSUserBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false
# # # FOS User Bundle
# fos_user:
#     db_driver: orm
#     firewall_name: main
#     user_class: GSEB\UserBundle\Entity\User
#     service:
#         mailer: fos_user.mailer.twig_swift
#     registration:
#         form:
#             type: FOS\UserBundle\Form\Type\RegistrationFormType
#             name: fos_user_registration_form
#             validation_groups: [Registration, Default]
#         confirmation:
#             enabled: true
#             template: '@FOSUser/Registration/email.txt.twig'
#     profile:
#         form:
#             type: FOS\UserBundle\Form\Type\ProfileFormType
#             validation_groups: [Profile, Default]
#     resetting:
#         email:
#             template: '@FOSUser/Resetting/email.txt.twig'
#     group:
#         group_class: GSEB\UserBundle\Entity\Group
#     from_email:
#         address: mail@domain.tld
#         sender_name: user