<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_cache.providers.doctrine.orm.demande_metadata_cache' shared service.

$this->services['doctrine_cache.providers.doctrine.orm.demande_metadata_cache'] = $instance = new \Doctrine\Common\Cache\ArrayCache();

$instance->setNamespace('sf_orm_demande_b0721a0c94bd89c6d603bb6c448aa6ffb0d7c5e73be1f9d77f638eb5a9765753');

return $instance;
