<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container67ekxe8\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container67ekxe8/appProdProjectContainer.php') {
    touch(__DIR__.'/Container67ekxe8.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container67ekxe8\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container67ekxe8\appProdProjectContainer(array(
    'container.build_hash' => '67ekxe8',
    'container.build_id' => '77244602',
    'container.build_time' => 1535385398,
), __DIR__.\DIRECTORY_SEPARATOR.'Container67ekxe8');
