<?php

namespace GSEB\MainBundle\Repository;

/**
 * RackspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RackspaceRepository extends \Doctrine\ORM\EntityRepository
{
}
