<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ60r6tu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ60r6tu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZ60r6tu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZ60r6tu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZ60r6tu\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Z60r6tu',
    'container.build_id' => '175a82f7',
    'container.build_time' => 1535561485,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ60r6tu');
